name: C++ Builder

on: 
  push:
    branches:
    - main

jobs:

  build-win:
   name: Windows Build
   runs-on: windows-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4
    - name: Build
      run: cl.exe /EHsc /O2 /std:c++17 /Fe:ffsearch.exe .\ffsearch.cpp
    - name: Test
      run: |
        .\ffsearch.exe index -f ".\test\names.csv" -c "full_name,nationality"
        .\ffsearch.exe search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffsearch_x64-windows
        path: 'ffsearch.exe'
    
  build-linux:
   name: Linux Build
   runs-on: ubuntu-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v3
    - name: Build
      run: g++ -std=c++17 ffsearch.cpp -o ffsearch -O3
    - name: Test
      run: |
        ./ffsearch index -f "./test/names.csv" -c "full_name,nationality"
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffsearch_x64-linux
        path: 'ffsearch'

  build-mac:
   name: Mac Build
   runs-on: macos-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v3
    - name: Build
      run: g++ -std=c++17 ffsearch.cpp -o ffsearch -O3
    - name: Test
      run: |
        ./ffsearch index -f "./test/names.csv" -c "full_name,nationality"
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffsearch_x64-macos
        path: 'ffsearch'
