name: C++ Builder

on: 
  push:
    branches:
    - main

jobs:

  build-win:
   name: Windows Build
   runs-on: windows-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4
    # run: | 
    #    $vsPath = & "$env:ProgramFiles (x86)\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath
    #    $vsDevCmdPath = Join-Path $vsPath "\Common7\Tools\VsDevCmd.bat"
    - name: Build
      run: |
        cl.exe /EHsc /GS /GL /Gy /Gm- /O2 /Oi /MD /sdl /std:c++17 /Fe:ffsearch.exe .\ffsearch.cpp
    - name: Generate Test
      run: |
        cl.exe /EHsc /GS /GL /Gy /Gm- /O2 /Oi /MD /sdl /std:c++17 /Fe:.\test\table_generator.exe .\test\table_generator.cpp
        .\test\table_generator.exe
    - name: Test Index
      run: .\ffsearch.exe index -f ".\test\names.csv" -c "full_name,nationality"
    - name: Test Search
      run: |
        .\ffsearch.exe search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
        .\ffsearch.exe search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
        .\ffsearch.exe search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffsearch_x64-windows
        path: 'ffsearch.exe'
    
  build-linux:
   name: Linux Build
   runs-on: ubuntu-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v3
    - name: Build
      run: g++ -std=c++17 ffsearch.cpp -o ffsearch -O3
    - name: Generate Test
      run: |
        g++ -std=c++17 ./test/table_generator.cpp -o ./test/table_generator -O3
        ./test/table_generator
    - name: Test Index
      run: ./ffsearch index -f "./test/names.csv" -c "full_name,nationality"
    - name: Test Search
      run: |
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffsearch_x64-linux
        path: 'ffsearch'

  build-mac:
   name: Mac Build
   runs-on: macos-latest
   steps:
    - name: Download Repository
      uses: actions/checkout@v3
    - name: Build
      run: g++ -std=c++17 ffsearch.cpp -o ffsearch -O3
    - name: Generate Test
      run: |
        g++ -std=c++17 ./test/table_generator.cpp -o ./test/table_generator -O3
        ./test/table_generator
    - name: Test Index
      run: ./ffsearch index -f "./test/names.csv" -c "full_name,nationality"
    - name: Test Search
      run: |
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
        ./ffsearch search -t "names" -c "full_name" -s "Nova Gatsby" -l 30 -f
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ffsearch_x64-macos
        path: 'ffsearch'
